### ISSUE TITLE
Add backward navigation

### ISSUE THREAD

**Issue by dafacto** [aurora-is-near/rainbow-bridge-frontend#252]
If I start here:

![](http://d.dafacto.com/LJp0GO+)

And proceed to here:

![](http://d.dafacto.com/HN264g+)

And at this point realize I've set the direction wrong, there's no way to navigate back. 

In the short term, we could add a back link next to cancel, but this reflects a fundamental problem with this Rainbow Bridge design. The whole direction setting and amounts configuration could be done on one screen, as we do in the Aurora Bridge.

**Comment by paouvrard** [comment]
@dafacto @corwinharrell
Adding a `Back` button seems like it would be a bit much, how about replacing the `Cancel` button with `Back` which would send the user back to the previous step (direction selection) ?

![image](https://user-images.githubusercontent.com/29397451/119520216-10971880-bdb5-11eb-906c-c0793eb4902c.png)

**Comment by corwinharrell** [comment]
> The whole direction setting and amounts configuration could be done on one screen, as we do in the Aurora Bridge.

Keep in mind that with the Aurora bridge simulation, there is no Log In / Connect wallet step which is necessary on both the Ethereum and NEAR sides. In fact, there is a degree of complexity absent from the Aurora simulation design that is necessary to allow the "Connect" step. (I'm not privy to an alternative design that I realize may exist)

The design of the MVP for the Rainbow Bridge UI was intentional to keep a separation of concerns to start. If the user is not even connected to both wallets, there's no point in showing them a complex swap UI if it would all be disabled by default (especially on mobile). Once they've established a connection on both ends (a process involving several clicks), they can then begin the transfer.

Now, this is not to say that you shouldn't be able to switch directions while in the middle of a transaction. **It certainly makes sense to accommodate this. Once the user is connected to both "ends" they should be able to switch the direction at will regardless of where they are in the process.** The decision to not include the ability to change directions mid-transfer was made primarily to reduce the scope in the short term.

Figured I'd just share some context on why it is the way it is.

**Comment by corwinharrell** [comment]
It's also worth mentioning that for web applications, it's often considered UX best practice to leverage native browser chrome and behavior as a means to navigate a single step back/forward. All browsers have a native back button, and also allow the user to swipe from the side of the screen to navigate back and forward. While custom back buttons do appear in web applications on occasion, it's generally considered to be an unnecessary duplication of native behavior that is already afforded to the user by their browser. The exception to this is when a user needs to navigate more than one step back in a multi-step flow, in which case breadcrumb patterns are typically used as a secondary means to navigate:

`one > two > three`

If we consider this, then "Cancel" actually serves a different purpose altogether, while the user can use the browser's back button or swipe navigation to get to the previous screen, resulting in a design that accommodates both needs.

**Comment by paouvrard** [comment]
Good points, thank you for sharing @corwinharrell 
I fixed the browser history navigation to allow users going back one step during the creation of a new transfer
And also renamed `Cancel` to `Back` on the transfer form.
https://github.com/aurora-is-near/rainbow-bridge-frontend/pull/233
